var bakeryCakesAndDairy = [
    {
     image_url: "https://www.bigbasket.com/media/uploads/p/s/40037475_12-fresho-signature-cinnamon-sticks.jpg",
     brandName: "FRESHO SIGNATURE",
     name: "Cinnamon Sticks",
     rating: 4.1,
     totalRatings: 6001,
     originalPrice: 95,
     offerPrice: 59,
     parentCategory: "Bakery, Cakes & Dairy",
     childCategory: "Bakery Snacks",
     subCategory: "Bread Sticks & Lavash",
    },
    {
     image_url: "https://www.bigbasket.com/media/uploads/p/s/40169958_3-the-bakers-dozen-lavash-100-wholewheat.jpg",
     brandName: "THE BAKER'S DOZEN",
     name: "Lavash - 100% Wholewheat",
     rating: 4.1,
     totalRatings: 6001,
     originalPrice: 119,
     offerPrice: 98.77,
     parentCategory: "Bakery, Cakes & Dairy",
     childCategory: "Bakery Snacks",
     subCategory: "Bread Sticks & Lavash",
    },
    {
     image_url: "https://www.bigbasket.com/media/uploads/p/s/40037497_15-fresho-signature-freshly-baked-multigrain-lavash.jpg",
     brandName: "FRESHO SIGNATURE",
     name: "Freshly Baked - Multigrain Lavash",
     rating: 4.1,
     totalRatings: 6001,
     originalPrice: 99,
     offerPrice: 72,
     parentCategory: "Bakery, Cakes & Dairy",
     childCategory: "Bakery Snacks",
     subCategory: "Bread Sticks & Lavash",
    },
    {
     image_url: "https://www.bigbasket.com/media/uploads/p/s/40037474_14-fresho-signature-spicy-cheese-straw.jpg",
     brandName: "FRESHO SIGNATURE",
     name: "Spicy Cheese Straw",
     rating: 4.1,
     totalRatings: 6001,
     originalPrice: 75,
     offerPrice: 65,
     parentCategory: "Bakery, Cakes & Dairy",
     childCategory: "Bakery Snacks",
     subCategory: "Bread Sticks & Lavash",
    },
    {
     image_url: "https://www.bigbasket.com/media/uploads/p/s/40192817_3-the-bakers-dozen-peri-peri-crackers-100-wholewheat.jpg",
     brandName: "THE BAKER'S DOZEN",
     name: "Peri Peri Crackers - 100% Wholewheat",
     rating: 4.1,
     totalRatings: 6001,
     originalPrice: 119,
     offerPrice: 111,
     parentCategory: "Bakery, Cakes & Dairy",
     childCategory: "Bakery Snacks",
     subCategory: "Bread Sticks & Lavash",
    },
    {
     image_url: "https://www.bigbasket.com/media/uploads/p/s/30004789_4-the-bakers-dozen-ragi-crackers.jpg",
     brandName: "THE BAKER'S DOZEN",
     name: "Ragi Crackers",
     rating: 4.1,
     totalRatings: 6001,
     originalPrice: 119,
     offerPrice: 98.50,
     parentCategory: "Bakery, Cakes & Dairy",
     childCategory: "Bakery Snacks",
     subCategory: "Bread Sticks & Lavash",
    },
    {
     image_url: "https://www.bigbasket.com/media/uploads/p/s/40129889_6-fresho-signature-snack-sticks-parmesan-cheese.jpg",
     brandName: "FRESHO SIGNATURE",
     name: "Parmesan Cheese Snack Sticks - Irresistible & Appetizing Snack",
     rating: 4.1,
     totalRatings: 6001,
     originalPrice: 119,
     offerPrice: 89,
     parentCategory: "Bakery, Cakes & Dairy",
     childCategory: "Bakery Snacks",
     subCategory: "Bread Sticks & Lavash",
    },
    {
     image_url: "https://www.bigbasket.com/media/uploads/p/s/30010746_4-wingreens-farms-baked-pita-bread-crisps-chilli-garlic.jpg",
     brandName: "WINGREENS FARMS",
     name: "Baked Pita Bread Crisps - Chilli & Garlic",
     rating: 4.1,
     totalRatings: 6001,
     originalPrice: 150,
     offerPrice: 127,
     parentCategory: "Bakery, Cakes & Dairy",
     childCategory: "Bakery Snacks",
     subCategory: "Bread Sticks & Lavash",
    },
    {
     image_url: "https://www.bigbasket.com/media/uploads/p/s/40212149_1-fresho-signature-garlic-herb-croutons.jpg",
     brandName: "FRESHO SIGNATURE",
     name: "Garlic & Herb Croutons Bites",
     rating: 4.1,
     totalRatings: 6001,
     originalPrice: 109,
     offerPrice: 75,
     parentCategory: "Bakery, Cakes & Dairy",
     childCategory: "Bakery Snacks",
     subCategory: "Breadcrumbs & Croutons",
    },
    {
     image_url: "https://www.bigbasket.com/media/uploads/p/s/40212148_1-fresho-signature-spicy-paprika-croutons.jpg",
     brandName: "FRESHO SIGNATURE",
     name: "Spicy Paprika Croutons Bites",
     rating: 4.1,
     totalRatings: 6001,
     originalPrice: 109,
     offerPrice: 75,
     parentCategory: "Bakery, Cakes & Dairy",
     childCategory: "Bakery Snacks",
     subCategory: "Breadcrumbs & Croutons",
    },
    {
     image_url: "https://www.bigbasket.com/media/uploads/p/s/40169954_3-the-bakers-dozen-garlic-bread-100-wholewheat.jpg",
     brandName: "THE BAKER'S DOZEN",
     name: "Garlic Bread - 100% Wholewheat",
     rating: 4.1,
     totalRatings: 6001,
     originalPrice: 99,
     offerPrice: 93,
     parentCategory: "Bakery, Cakes & Dairy",
     childCategory: "Bakery Snacks",
     subCategory: "Cheese & Garlic Bread",
    },
    {
     image_url: "https://www.bigbasket.com/media/uploads/p/s/30010746_4-wingreens-farms-baked-pita-bread-crisps-chilli-garlic.jpg",
     brandName: "WINGREENS FARMS",
     name: "Baked Pita Bread Crisps - Chilli & Garlic",
     rating: 4.1,
     totalRatings: 6001,
     originalPrice: 150,
     offerPrice: 127,
     parentCategory: "Bakery, Cakes & Dairy",
     childCategory: "Bakery Snacks",
     subCategory: "Cheese & Garlic Bread",
    },
    {
     image_url: "https://www.bigbasket.com/media/uploads/p/s/40169966_3-the-bakers-dozen-sandwich-loaf-100-whole-wheat.jpg",
     brandName: "THE BAKER'S DOZEN",
     name: "Sandwich Loaf - 100% Whole Wheat",
     rating: 4.1,
     totalRatings: 6001,
     originalPrice: 59,
     offerPrice: 54.50,
     parentCategory: "Bakery, Cakes & Dairy",
     childCategory: "Breads & Buns",
     subCategory: "Brown, Wheat & Multigrain",
    },
    {
     image_url: "https://www.bigbasket.com/media/uploads/p/s/40169960_3-the-bakers-dozen-multigrain-loaf-100-wholewheat.jpg",
     brandName: "THE BAKER'S DOZEN",
     name: "Multigrain Loaf 100% Wholewheat",
     rating: 4.1,
     totalRatings: 6001,
     originalPrice: 65,
     offerPrice: 61.10,
     parentCategory: "Bakery, Cakes & Dairy",
     childCategory: "Breads & Buns",
     subCategory: "Brown, Wheat & Multigrain",
    },
    {
     image_url: "https://www.bigbasket.com/media/uploads/p/s/40169964_3-the-bakers-dozen-ragi-loaf.jpg",
     brandName: "THE BAKER'S DOZEN",
     name: "Ragi Loaf",
     rating: 4.1,
     totalRatings: 6001,
     originalPrice: 59,
     offerPrice: 48.97,
     parentCategory: "Bakery, Cakes & Dairy",
     childCategory: "Breads & Buns",
     subCategory: "Brown, Wheat & Multigrain",
    },
    {
     image_url: "https://www.bigbasket.com/media/uploads/p/s/40169962_3-the-bakers-dozen-pizza-base-sourdough-100-wholewheat.jpg",
     brandName: "THE BAKER'S DOZEN",
     name: "Pizza Base - Sourdough 100% Wholewheat",
     rating: 4.1,
     totalRatings: 6001,
     originalPrice: 89,
     offerPrice: 83.66,
     parentCategory: "Bakery, Cakes & Dairy",
     childCategory: "Breads & Buns",
     subCategory: "Buns, Pavs & Pizza Base",
    },
    {
     image_url: "https://www.bigbasket.com/media/uploads/p/s/40192820_2-the-bakers-dozen-100-whole-wheat-pav-sourdough.jpg",
     brandName: "THE BAKER'S DOZEN",
     name: "100% Whole Wheat Pav Sourdough",
     rating: 4.1,
     totalRatings: 6001,
     originalPrice: 49,
     offerPrice: 46.60,
     parentCategory: "Bakery, Cakes & Dairy",
     childCategory: "Breads & Buns",
     subCategory: "Buns, Pavs & Pizza Base",
    },
    {
     image_url: "https://www.bigbasket.com/media/uploads/p/s/40262649_1-haiku-milk-bread-soft-rich-in-protein-calcium-healthy-breakfast.jpg",
     brandName: "HAIKU",
     name: "Haiku Milk Bread - Soft, Rich In Protein & Calcium, Healthy Breakfast",
     rating: 4.1,
     totalRatings: 6001,
     originalPrice: 45,
     offerPrice: 42.30,
     parentCategory: "Bakery, Cakes & Dairy",
     childCategory: "Breads & Buns",
     subCategory: "Milk, White & Sandwich",
    },
    {
     image_url: "https://www.bigbasket.com/media/uploads/p/s/1222400_3-fresho-signature-pinwheel-cookies-150-g-plum-cake-500-g-french-heart-cinnamon-roll-150-g.jpg",
     brandName: "FRESHO SIGNATURE",
     name: "Pinwheel Cookies 150 g + Plum Cake 500 g + French Heart Cinnamon Roll 150g",
     rating: 4.1,
     totalRatings: 6001,
     originalPrice: 1123,
     offerPrice: 1031.21,
     parentCategory: "Bakery, Cakes & Dairy",
     childCategory: "Cakes & Pastries",
     subCategory: "Birthday & Party Cakes",
    },
    {
     image_url: "https://www.bigbasket.com/media/uploads/p/s/1222401_3-fresho-signature-french-heart-cinnamon-roll-150-g-assorted-ginger-bread-cookies.jpg",
     brandName: "FRESHO SIGNATURE",
     name: "French Heart Cinnamon Roll 150 g + Assorted Ginger Bread Cookies, Combo",
     rating: 4.1,
     totalRatings: 6001,
     originalPrice: 388,
     offerPrice: 353,
     parentCategory: "Bakery, Cakes & Dairy",
     childCategory: "Cakes & Pastries",
     subCategory: "Birthday & Party Cakes",
    },
    {
     image_url: "https://www.bigbasket.com/media/uploads/p/s/1222402_3-fresho-signature-assorted-ginger-bread-cookies-150-g-plum-cake-french-heart-cinnamon-roll.jpg",
     brandName: "FRESHO SIGNATURE",
     name: "Christmas Combo - Plum Cake 750g + Cookies (150gx2) + Cinnamon Roll 150g, Combo",
     rating: 4.1,
     totalRatings: 6001,
     originalPrice: 1332,
     offerPrice: 1231,
     parentCategory: "Bakery, Cakes & Dairy",
     childCategory: "Cakes & Pastries",
     subCategory: "Birthday & Party Cakes",
    },
    {
     image_url: "https://www.bigbasket.com/media/uploads/p/s/1222399_3-fresho-signature-ginger-bread-cookies-150-g-plum-cake-250-g-pinwheel-cookies-150-g.jpg",
     brandName: "FRESHO SIGNATURE",
     name: "Ginger Bread Cookies 150 g + Plum Cake 250 g + Pinwheel Cookies 150 g, Combo",
     rating: 4.1,
     totalRatings: 6001,
     originalPrice: 757,
     offerPrice: 703,
     parentCategory: "Bakery, Cakes & Dairy",
     childCategory: "Cakes & Pastries",
     subCategory: "Birthday & Party Cakes",
    },
    {
     image_url: "https://www.bigbasket.com/media/uploads/p/s/40052061_3-elite-dreams-cup-cake-choco.jpg",
     brandName: "ELITE",
     name: "Dreams Cup Cake - Choco, 15 g",
     rating: 4.1,
     totalRatings: 6001,
     originalPrice: 5,
     offerPrice: 4.70,
     parentCategory: "Bakery, Cakes & Dairy",
     childCategory: "Cakes & Pastries",
     subCategory: "Muffins & Cup Cakes",
    },
    {
     image_url: "https://www.bigbasket.com/media/uploads/p/s/40052062_4-elite-dreams-cup-cake-butter.jpg",
     brandName: "ELITE",
     name: "Dreams Cup Cake - Butter, 140 g (Pack of 6)",
     rating: 4.1,
     totalRatings: 6001,
     originalPrice: 50,
     offerPrice: 47,
     parentCategory: "Bakery, Cakes & Dairy",
     childCategory: "Cakes & Pastries",
     subCategory: "Muffins & Cup Cakes",
    },
    {
     image_url: "https://www.bigbasket.com/media/uploads/p/s/40103027_5-winkies-centre-filled-cup-cake-with-vanilla-cream.jpg",
     brandName: "WINKIES",
     name: "Centre Filled Cup Cake - with Vanilla Cream, 30 g",
     rating: 4.1,
     totalRatings: 6001,
     originalPrice: 10,
     offerPrice: 9.40,
     parentCategory: "Bakery, Cakes & Dairy",
     childCategory: "Cakes & Pastries",
     subCategory: "Muffins & Cup Cakes",
    },
    {
     image_url: "https://www.bigbasket.com/media/uploads/p/s/40188424_6-the-bakers-dozen-eggless-cupcakes-chocolate-overload.jpg",
     brandName: "THE BAKER'S DOZEN",
     name: "Eggless Cupcakes - Chocolate Overload, 150 g",
     rating: 4.1,
     totalRatings: 6001,
     originalPrice: 159,
     offerPrice: 149.50,
     parentCategory: "Bakery, Cakes & Dairy",
     childCategory: "Cakes & Pastries",
     subCategory: "Muffins & Cup Cakes",
    },
    {
     image_url: "https://www.bigbasket.com/media/uploads/p/s/40169133_2-elite-dates-pudding-cake.jpg",
     brandName: "ELITE",
     name: "Dates Pudding Cake, 250 g Box",
     rating: 4.1,
     totalRatings: 6001,
     originalPrice: 130,
     offerPrice: 122.50,
     parentCategory: "Bakery, Cakes & Dairy",
     childCategory: "Cakes & Pastries",
     subCategory: "Pastries & Brownies",
    },
    {
     image_url: "https://www.bigbasket.com/media/uploads/p/s/40169146_2-elite-jackfruit-pudding-cake-non-veg.jpg",
     brandName: "ELITE",
     name: "Jackfruit Pudding Cake - Non-Veg, 250 g Box",
     rating: 4.1,
     totalRatings: 6001,
     originalPrice: 130,
     offerPrice: 122.50,
     parentCategory: "Bakery, Cakes & Dairy",
     childCategory: "Cakes & Pastries",
     subCategory: "Pastries & Brownies",
    },
    {
     image_url: "https://www.bigbasket.com/media/uploads/p/s/40198332_1-britannia-fudge-it-chocolate-brownie.jpg",
     brandName: "BRITANNIA",
     name: "Fudge It - Chocolate Brownie, 120 g",
     rating: 4.1,
     totalRatings: 6001,
     originalPrice: 60,
     offerPrice: 43,
     parentCategory: "Bakery, Cakes & Dairy",
     childCategory: "Cakes & Pastries",
     subCategory: "Tea Cakes & Slice Cakes",
    },
    {
     image_url: "https://www.bigbasket.com/media/uploads/p/s/40167042_8-britannia-treat-croissant-vanilla-creme-roll-100-veg.jpg",
     brandName: "BRITANNIA",
     name: "Croissant - Vanilla Creme Filling, 100% Veg, Soft, 45 g",
     rating: 4.1,
     totalRatings: 6001,
     originalPrice: 20,
     offerPrice: 18.80,
     parentCategory: "Bakery, Cakes & Dairy",
     childCategory: "Cakes & Pastries",
     subCategory: "Tea Cakes & Slice Cakes",
    },
    {
     image_url: "https://www.bigbasket.com/media/uploads/p/s/40167043_9-britannia-treat-croissant-cocoa-creme-roll-100-veg.jpg",
     brandName: "BRITANNIA",
     name: "Croissant - Cocoa Creme Filling, 100% Veg, Soft, 45 g",
     rating: 4.1,
     totalRatings: 6001,
     originalPrice: 20,
     offerPrice: 18.80,
     parentCategory: "Bakery, Cakes & Dairy",
     childCategory: "Cakes & Pastries",
     subCategory: "Tea Cakes & Slice Cakes",
    },
    {
     image_url: "https://www.bigbasket.com/media/uploads/p/s/40200453_2-bb-popular-bakery-biscuit-tooti-fruity.jpg",
     brandName: "BB POPULAR",
     name: "Bakery Biscuit - Tooti Fruity, 200 g",
     rating: 4.1,
     totalRatings: 6001,
     originalPrice: 145,
     offerPrice: 136.60,
     parentCategory: "Bakery, Cakes & Dairy",
     childCategory: "Cookies, Rusk & Khari",
     subCategory: "Bakery Biscuits, Cookies",
    },
    {
     image_url: "https://www.bigbasket.com/media/uploads/p/s/40106019_9-tasties-biscuits-osmania.jpg",
     brandName: "TASTIES",
     name: "Biscuits - Osmania, 200 g",
     rating: 4.1,
     totalRatings: 6001,
     originalPrice: 99,
     offerPrice: 89,
     parentCategory: "Bakery, Cakes & Dairy",
     childCategory: "Cookies, Rusk & Khari",
     subCategory: "Bakery Biscuits, Cookies",
    },
    {
     image_url: "https://www.bigbasket.com/media/uploads/p/s/40200455_2-bb-popular-bakery-biscuit-badam.jpg",
     brandName: "BB POPULAR",
     name: "Bakery Biscuit - Badam, 200 g",
     rating: 4.1,
     totalRatings: 6001,
     originalPrice: 145,
     offerPrice: 136.50,
     parentCategory: "Bakery, Cakes & Dairy",
     childCategory: "Cookies, Rusk & Khari",
     subCategory: "Bakery Biscuits, Cookies",
    },
    {
     image_url: "https://www.bigbasket.com/media/uploads/p/s/40106022_7-tasties-khari-maska.jpg",
     brandName: "TASTIES",
     name: "Khari - Maska, 200 g",
     rating: 4.1,
     totalRatings: 6001,
     originalPrice: 109,
     offerPrice: 95,
     parentCategory: "Bakery, Cakes & Dairy",
     childCategory: "Cookies, Rusk & Khari",
     subCategory: "Khari & Cream Rolls",
    },
    {
     image_url: "https://www.bigbasket.com/media/uploads/p/s/40106025_7-tasties-khari-jeera.jpg",
     brandName: "TASTIES",
     name: "Khari - Jeera, 200 g",
     rating: 4.1,
     totalRatings: 6001,
     originalPrice: 119,
     offerPrice: 99,
     parentCategory: "Bakery, Cakes & Dairy",
     childCategory: "Cookies, Rusk & Khari",
     subCategory: "Khari & Cream Rolls",
    },
    {
     image_url: "https://www.bigbasket.com/media/uploads/p/s/40106023_9-tasties-khari-masala.jpg",
     brandName: "TASTIES",
     name: "Khari - Masala, 200 g",
     rating: 4.1,
     totalRatings: 6001,
     originalPrice: 150,
     offerPrice: 127,
     parentCategory: "Bakery, Cakes & Dairy",
     childCategory: "Cookies, Rusk & Khari",
     subCategory: "Khari & Cream Rolls",
    },
    {
     image_url: "https://www.bigbasket.com/media/uploads/p/s/40094947_11-fresho-signature-almond-biscuit-sticks.jpg",
     brandName: "FRESHO SIGNATURE",
     name: "Almond Biscuit Sticks, 150 g",
     rating: 4.1,
     totalRatings: 6001,
     originalPrice: 249,
     offerPrice: 169,
     parentCategory: "Bakery, Cakes & Dairy",
     childCategory: "Cookies, Rusk & Khari",
     subCategory: "Premium Cookies",
    },
    {
     image_url: "https://www.bigbasket.com/media/uploads/p/s/40055540_6-fresho-signature-cookies-dark-chocochip-chewy.jpg",
     brandName: "FRESHO SIGNATURE",
     name: "Cookies - Dark Chocochip, Chewy, 150 g",
     rating: 4.1,
     totalRatings: 6001,
     originalPrice: 199,
     offerPrice: 139,
     parentCategory: "Bakery, Cakes & Dairy",
     childCategory: "Cookies, Rusk & Khari",
     subCategory: "Premium Cookies",
    },
    {
     image_url: "https://www.bigbasket.com/media/uploads/p/s/800000371_2-millet-cookies-12-grains-with-organic-jaggery.jpg",
     brandName: "MILLET COOKIES",
     name: "12 Grains With Organic Jaggery, 150 g",
     rating: 4.1,
     totalRatings: 6001,
     originalPrice: 60,
     offerPrice: 56.40,
     parentCategory: "Bakery, Cakes & Dairy",
     childCategory: "Cookies, Rusk & Khari",
     subCategory: "Premium Cookies",
    },
    {
     image_url: "https://www.bigbasket.com/media/uploads/p/s/312169_15-britannia-bake-rusk-toast.jpg",
     brandName: "BRITANNIA",
     name: "Toastea Premium Bake Rusk - With Real Elaichi, Crunchy, Zero Trans Fat, 150 g",
     rating: 4.1,
     totalRatings: 6001,
     originalPrice: 30,
     offerPrice: 28.80,
     parentCategory: "Bakery, Cakes & Dairy",
     childCategory: "Cookies, Rusk & Khari",
     subCategory: "Rusks",
    },
    {
     image_url: "https://www.bigbasket.com/media/uploads/p/s/40101048_10-parle-rusk-real-elaichi.jpg",
     brandName: "PARLE",
     name: "Rusk Real Elaichi, 327 g (Get 27 g Extra)",
     rating: 4.1,
     totalRatings: 6001,
     originalPrice: 150,
     offerPrice: 127,
     parentCategory: "Bakery, Cakes & Dairy",
     childCategory: "Cookies, Rusk & Khari",
     subCategory: "Rusks",
    },
    {
     image_url: "https://www.bigbasket.com/media/uploads/p/s/407839_8-britannia-toastea-milk-rusk-with-goodness-of-milk-wheat.jpg",
     brandName: "BRITANNIA",
     name: "Toastea Milk/Doodh Rusk - Crunchy, Zero Trans Fat, Ready To Eat, 182 g",
     rating: 4.1,
     totalRatings: 6001,
     originalPrice: 35,
     offerPrice: 32.20,
     parentCategory: "Bakery, Cakes & Dairy",
     childCategory: "Cookies, Rusk & Khari",
     subCategory: "Rusks",
    },
    {
     image_url: "https://www.bigbasket.com/media/uploads/p/s/40106015_11-tasties-rusk-suji-elaichi.jpg",
     brandName: "TASTIES",
     name: "Rusk - Suji & Elaichi, 200 g",
     rating: 4.1,
     totalRatings: 6001,
     originalPrice: 55,
     offerPrice: 39,
     parentCategory: "Bakery, Cakes & Dairy",
     childCategory: "Cookies, Rusk & Khari",
     subCategory: "Rusks",
    },
    {
     image_url: "https://www.bigbasket.com/media/uploads/p/s/40119204_3-nutralite-premium-table-spread-garlic-oregano-enriched-with-omega-3.jpg",
     brandName: "NUTRALITE",
     name: "Healthier & Delicious Garlic & Oregano Fat Spread, 100 g Carton",
     rating: 4.1,
     totalRatings: 6001,
     originalPrice: 50,
     offerPrice: 47,
     parentCategory: "Bakery, Cakes & Dairy",
     childCategory: "Dairy",
     subCategory: "Butter & Margarine",
    },
    {
     image_url: "https://www.bigbasket.com/media/uploads/p/s/40290833_1-nutralite-doodh-shakti-probiotic-butter-spread-supports-immunity.jpg",
     brandName: "NUTRALITE",
     name: "DoodhShakti Probiotic Butter Spread - Salted, Supports Gut Health, 500 g",
     rating: 4.1,
     totalRatings: 6001,
     originalPrice: 279,
     offerPrice: 245.50,
     parentCategory: "Bakery, Cakes & Dairy",
     childCategory: "Dairy",
     subCategory: "Butter & Margarine",
    },
    {
     image_url: "https://www.bigbasket.com/media/uploads/p/s/161899_9-amul-masti-buttermilk-spice.jpg",
     brandName: "AMUL",
     name: "Masti Buttermilk - Spice, 200 ml Carton",
     rating: 4.1,
     totalRatings: 6001,
     originalPrice: 15,
     offerPrice: 14.10,
     parentCategory: "Bakery, Cakes & Dairy",
     childCategory: "Dairy",
     subCategory: "Buttermilk & Lassi",
    },
    {
     image_url: "https://www.bigbasket.com/media/uploads/p/s/40193425_6-paper-boat-pudina-buttermilk.jpg",
     brandName: "PAPER BOAT",
     name: "Pudina Buttermilk, 250 ml",
     rating: 4.1,
     totalRatings: 6001,
     originalPrice: 30,
     offerPrice: 28.20,
     parentCategory: "Bakery, Cakes & Dairy",
     childCategory: "Dairy",
     subCategory: "Buttermilk & Lassi",
    },
    {
     image_url: "https://www.bigbasket.com/media/uploads/p/s/40013013_2-amul-lassi-rose-flavor.jpg",
     brandName: "AMUL",
     name: "Lassi - Rose Flavour, Source of Calcium & Protein, 200 ml Carton",
     rating: 4.1,
     totalRatings: 6001,
     originalPrice: 150,
     offerPrice: 127,
     parentCategory: "Bakery, Cakes & Dairy",
     childCategory: "Dairy",
     subCategory: "Buttermilk & Lassi",
    },
    {
     image_url: "https://www.bigbasket.com/media/uploads/p/s/40262045_4-milky-mist-lassi-blueberry-hydrating-creamy.jpg",
     brandName: "MILKY MIST",
     name: "Lassi - Blueberry, UHT, Drink Based On Fermented Milk, Rich Flavour, 200 ml",
     rating: 4.1,
     totalRatings: 6001,
     originalPrice: 150,
     offerPrice: 127,
     parentCategory: "Bakery, Cakes & Dairy",
     childCategory: "Dairy",
     subCategory: "Buttermilk & Lassi",
    },
    {
     image_url: "https://www.bigbasket.com/media/uploads/p/s/40020214_12-nestle-everyday-dairy-whitener-milk-powder-for-tea.jpg",
     brandName: "NESTLE",
     name: "Everyday Dairy Whitener - Milk Powder For Tea, 15 g Pouch",
     rating: 4.1,
     totalRatings: 6001,
     originalPrice: 10,
     offerPrice: 9.40,
     parentCategory: "Bakery, Cakes & Dairy",
     childCategory: "Dairy",
     subCategory: "Condensed, Powdered Milk",
    },
    {
     image_url: "https://www.bigbasket.com/media/uploads/p/s/40058175_2-amul-amulya-dairy-whitener.jpg",
     brandName: "AMULYA",
     name: "Dairy Whitener, 1 kg Pouch",
     rating: 4.1,
     totalRatings: 6001,
     originalPrice: 430,
     offerPrice: 404.50,
     parentCategory: "Bakery, Cakes & Dairy",
     childCategory: "Dairy",
     subCategory: "Condensed, Powdered Milk",
    },
    {
     image_url: "https://www.bigbasket.com/media/uploads/p/s/266070_11-nestle-milkmaid-sweetened-condensed-milk.jpg",
     brandName: "NESTLE",
     name: "Milkmaid Partly Skimmed Sweetened Condensed Milk, 380 g Tin",
     rating: 4.1,
     totalRatings: 6001,
     originalPrice: 144,
     offerPrice: 135.50,
     parentCategory: "Bakery, Cakes & Dairy",
     childCategory: "Dairy",
     subCategory: "Condensed, Powdered Milk",
    },
    {
     image_url: "https://www.bigbasket.com/media/uploads/p/s/40088412_6-hersheys-milk-shake-chocolate.jpg",
     brandName: "HERSHEYS",
     name: "Milkshake - Chocolate, 180 ml",
     rating: 4.1,
     totalRatings: 6001,
     originalPrice: 40,
     offerPrice: 34,
     parentCategory: "Bakery, Cakes & Dairy",
     childCategory: "Dairy",
     subCategory: "Flavoured, Soya Milk",
    },
    {
     image_url: "https://www.bigbasket.com/media/uploads/p/s/40103749_6-cavins-milkshake-chocolate.jpg",
     brandName: "CAVINS",
     name: "Chocolate Milkshake - With Zinc, Vitamin A & D Added, Supports Immunity, 1 L",
     rating: 4.1,
     totalRatings: 6001,
     originalPrice: 240,
     offerPrice: 168,
     parentCategory: "Bakery, Cakes & Dairy",
     childCategory: "Dairy",
     subCategory: "Flavoured, Soya Milk",
    },
    {
     image_url: "https://www.bigbasket.com/media/uploads/p/s/264208_2-heritage-flavoured-milk-badam.jpg",
     brandName: "HERITAGE",
     name: "Flavoured Milk - Badam, 200 ml Bottle",
     rating: 4.1,
     totalRatings: 6001,
     originalPrice: 30,
     offerPrice: 28,
     parentCategory: "Bakery, Cakes & Dairy",
     childCategory: "Dairy",
     subCategory: "Flavoured, Soya Milk",
    },
 //    {
 //     image_url: "",
 //     brandName: "",
 //     name: "",
 //     rating: 4.1,
 //     totalRatings: 6001,
 //     originalPrice: 150,
 //     offerPrice: 127,
 //     parentCategory: "Bakery, Cakes & Dairy",
 //     childCategory: "Dairy",
 //     subCategory: "",
 //    },

    
]
var currentProduct = JSON.parse(localStorage.getItem("showProduct"));
console.log(currentProduct);
displayProduct(currentProduct);

function displayProduct(product) {
    var div = document.createElement("div");
    // div.setAttribute("class", "productImage");
    
    var image = document.createElement("img");
    image.setAttribute("src", "https://www.bigbasket.com/media/uploads/p/l/100285703_15-nandini-goodlife-toned-milk.jpg");
    // image.setAttribute("src", product.image_url);
    image.setAttribute("alt", product.name);

    document.getElementById("image").append(image);

    var brandName = document.createElement("p");
    brandName.textContent = product.brandName;

    var name = document.createElement("p");
    name.textContent = product.name;

    var originalPrice = document.createElement("p");
    originalPrice.textContent = "₹ " + product.originalPrice;

    var offerPrice = document.createElement("p");
    offerPrice.textContent = "₹ " + product.offerPrice;

    var priceDetails = document.createElement("p");
    priceDetails.textContent = "(Inclusive of all taxes)";

    var rating = document.createElement("p");
    rating.textContent = product.rating;

    var totalRatings = document.createElement("p");
    totalRatings.textContent = product.totalRatings;

    var ratingDiv = document.createElement("div");
    ratingDiv.setAttribute("class", "ratingInProductPage")
    ratingDiv.appendChild(rating);
    ratingDiv.appendChild(totalRatings);

    var button = document.createElement("button");
    button.textContent = "ADD TO BASKET";
    
    var deliveryInformation = document.createElement("p");
    deliveryInformation.textContent = "Standard: Tomorrow Evening";

    div.append(brandName, name, originalPrice, offerPrice, priceDetails, ratingDiv, button, deliveryInformation);

    document.getElementById("content").append(div);
}

// var leftBar = document.getElementById("leftContent");

// var category = document.createElement("h6");
// category.textContent = "category";

// var parentCategory = document.createElement("h6");
// parentCategory.textContent = 
/*
var output = []

output = users.filter(function(element) {
    return element.place == "Banglore";
}).map(function(element, index, array) {
    return element.firstName + " " + element.lastName
});
*/